// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDixHda4nhYvtg-n1gcchn6G6mhg8UdPOA',
    appId: '1:813031529507:android:2e34c6a9e32fea825ea596',
    messagingSenderId: '813031529507',
    projectId: 'chum-app-f0959',
    storageBucket: 'chum-app-f0959.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Fp2KJxHW9Dgg-XJANH1EkxGqkCAvDSQ',
    appId: '1:813031529507:ios:9d150a66fa22b77b5ea596',
    messagingSenderId: '813031529507',
    projectId: 'chum-app-f0959',
    storageBucket: 'chum-app-f0959.appspot.com',
    androidClientId: '813031529507-m52p3io4t0ojmu98ccrovpv63nb8t74j.apps.googleusercontent.com',
    iosClientId: '813031529507-kq6hh7h67m06ca097j0m6677hpqpob4m.apps.googleusercontent.com',
    iosBundleId: 'chumcaphe.vn.chum2',
  );
}
